---
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - vendor/**/*
    - pkg/**/*
    - spec/fixtures/**/*
    - lib/rzo/trollop.rb
    - Vagrantfile

# Cop's to ignore
Style/RedundantReturn:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/UnneededDisable:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

# if / else / end is more clear than conditional assignment
Style/ConditionalAssignment:
  Enabled: false

# With this enabled it suggests a change that will break the Gemfile
# Also, if name = hsh['name'] is really useful to avoid Unknown method called on
# nil object errors.
Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Enabled: false

# This is a good idea, but does not line up the rest of the lines making it
# harder to read
Layout/IndentHash:
  Enabled: false

Style/Next:
  Enabled: false

# If enabled, this cop makes it harder to understand the logic
Style/NonNilCheck:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

# Cop's that require ruby >= 1.9
Style/HashSyntax:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

# too many lines is the nature of a Vagrantfile
Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Style/IfInsideElse:
  Enabled: false
