---
sudo: false
language: ruby

notifications:
  email: false

rvm:
  - 2.4.4
  - 2.5.1

script:
  - 'bundle exec rake validate rubocop'
  - 'bundle exec rspec'
  - 'scripts/functional_gem_behavior.sh'
